language: python

python:
    - '2.6'
    - '2.7'

install:
    - "pip install -r requirements.txt"

script:
    - py.test --doctest-modules -v --cov youtube_api --cov-report term-missing

after_success:
    - coveralls