language: python

python:
    - '2.6'
    - '2.7'
    - '3.3'
    - '3.4'

install:
    - "pip install -r requirements/test.txt"

script:
    - py.test --doctest-modules -v --cov youtube_api --cov-report term-missing

after_success:
    - coveralls